# swag

name: ZippingCit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.set_tag.outputs.new_tag }}
    steps:
      
      - uses: actions/checkout@main

      - name: zip ts
        run: zip -r krscit.zip assets/ pack.mcmeta
          rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
          
      - name: bump-n-push
        id: tag_version
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: tag it
        id: set_tag
        run: echo "new_tag=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV

      - name: making release 
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_tag }}
          release_name: Release ${{ env.new_tag }}
          draft: false
          prerelease: false

      - name: and finish him (uploadind zips)
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/krscit.zip
          asset_name: krscit.zip
          asset_content_type: application/zip
